#Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=mysql://root:frdBvjmlGdKBlCMyhAwZvYBTmMXsrccy@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=frdBvjmlGdKBlCMyhAwZvYBTmMXsrccy

#  JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update